"use client";

import { useMemo } from "react";
import { useSelector } from "react-redux";
import { RootState } from "@/app/Store/Store";
import { motion } from "framer-motion";
import {
  Gauge,
  MessageSquare,
  SmilePlus,
  ThumbsUp,
  ThumbsDown,
  Sparkles,
} from "lucide-react";
import ProtectedRoute from "@/app/components/ProtectedRoute";

const fadeUp = {
  hidden: { opacity: 0, y: 15 },
  visible: { opacity: 1, y: 0, transition: { duration: 0.5 } },
};

export default function FeedbackSection() {
  const feedback = useSelector(
    (state: RootState) => state.feedbackReducer.feedback?.report
  );

  const memoizedFeedback = useMemo(() => feedback, [feedback]);

  if (!memoizedFeedback) {
    return (
      <div className="text-center text-voxy-muted mt-20">
        <p>No feedback report available. Please complete your interview first.</p>
      </div>
    );
  }

  const {
    technicalScore = 0,
    communication,
    confidence,
    strengths = [],
    weaknesses = [],
    summary,
  } = memoizedFeedback;

  return (
    <ProtectedRoute>
      <motion.div
        variants={fadeUp}
        initial="hidden"
        animate="visible"
        className="space-y-10 max-w-5xl mx-auto px-4 md:px-8 pb-20"
      >
        {/* HEADER */}
        <section className="text-center space-y-2">
          <h2 className="text-3xl md:text-4xl font-bold text-voxy-text tracking-tight">
            Recent Interview Feedback
          </h2>
          <p className="text-voxy-muted text-sm md:text-base">
            Here’s your most recent feedback generated by the AI interviewer.
          </p>
        </section>

        {/* TECHNICAL SCORE */}
        <motion.section
          whileHover={{ scale: 1.02 }}
          className="max-w-md mx-auto bg-voxy-surface border border-voxy-border rounded-2xl p-8 backdrop-blur-xl shadow-lg text-center"
        >
          <div className="relative w-40 h-40 mx-auto mb-6">
            <svg className="w-full h-full transform -rotate-90">
              <circle
                cx="80"
                cy="80"
                r="70"
                stroke="var(--color-voxy-border)"
                strokeWidth="10"
                fill="none"
              />
              <motion.circle
                cx="80"
                cy="80"
                r="70"
                stroke="url(#voxyGradient)"
                strokeWidth="10"
                fill="none"
                strokeLinecap="round"
                initial={{ strokeDasharray: 0, strokeDashoffset: 440 }}
                animate={{
                  strokeDasharray: 440,
                  strokeDashoffset: 440 - (440 * technicalScore) / 10,
                }}
                transition={{ duration: 1.5, ease: "easeOut" }}
              />
              <defs>
                <linearGradient id="voxyGradient" x1="0%" y1="0%" x2="100%" y2="0%">
                  <stop offset="0%" stopColor="var(--color-voxy-primary)" />
                  <stop offset="100%" stopColor="var(--color-voxy-accent)" />
                </linearGradient>
              </defs>
            </svg>

            <div className="absolute inset-0 flex flex-col items-center justify-center">
              <Gauge size={28} className="text-voxy-primary mb-1" />
              <p className="text-3xl font-bold text-voxy-text">
                {technicalScore}/10
              </p>
              <span className="text-xs text-voxy-muted">Technical Score</span>
            </div>
          </div>
        </motion.section>

        {/* COMMUNICATION & CONFIDENCE */}
        <section className="grid grid-cols-1 sm:grid-cols-2 gap-6">
          {[
            {
              title: "Communication",
              icon: <MessageSquare className="text-voxy-primary" size={20} />,
              content: communication,
            },
            {
              title: "Confidence",
              icon: <SmilePlus className="text-voxy-secondary" size={20} />,
              content: confidence,
            },
          ].map(({ title, icon, content }) => (
            <motion.article
              key={title}
              whileHover={{ scale: 1.02 }}
              transition={{ type: "spring", stiffness: 180, damping: 16 }}
              className="p-6 rounded-2xl border border-voxy-border bg-voxy-surface backdrop-blur-lg shadow-md"
            >
              <div className="flex items-center gap-3 mb-3">
                {icon}
                <h3 className="text-lg font-semibold text-voxy-text">{title}</h3>
              </div>
              <p className="text-sm text-voxy-muted leading-relaxed">
                {content || "No data available."}
              </p>
            </motion.article>
          ))}
        </section>

        {/* STRENGTHS & WEAKNESSES */}
        <section className="grid grid-cols-1 lg:grid-cols-2 gap-6">
          <motion.article
            whileHover={{ scale: 1.02 }}
            className="p-6 rounded-2xl border border-voxy-border bg-gradient-to-br from-voxy-primary/10 to-voxy-surface shadow-md"
          >
            <div className="flex items-center gap-3 mb-4">
              <ThumbsUp className="text-voxy-primary" size={20} />
              <h3 className="text-lg font-semibold text-voxy-text">Strengths</h3>
            </div>
            {strengths.length ? (
              <ul className="space-y-2 text-sm text-voxy-muted">
                {strengths.map((point, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-voxy-primary mt-0.5">•</span> {point}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-voxy-muted italic">No strengths recorded.</p>
            )}
          </motion.article>

          <motion.article
            whileHover={{ scale: 1.02 }}
            className="p-6 rounded-2xl border border-voxy-border bg-gradient-to-br from-voxy-accent/10 to-voxy-surface shadow-md"
          >
            <div className="flex items-center gap-3 mb-4">
              <ThumbsDown className="text-voxy-accent" size={20} />
              <h3 className="text-lg font-semibold text-voxy-text">Weaknesses</h3>
            </div>
            {weaknesses.length ? (
              <ul className="space-y-2 text-sm text-voxy-muted">
                {weaknesses.map((point, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-voxy-accent mt-0.5">•</span> {point}
                  </li>
                ))}
              </ul>
            ) : (
              <p className="text-sm text-voxy-muted italic">No weaknesses recorded.</p>
            )}
          </motion.article>
        </section>

        {/* SUMMARY */}
        <motion.section
          whileHover={{ scale: 1.01 }}
          transition={{ type: "spring", stiffness: 160, damping: 14 }}
          className="p-6 rounded-2xl border border-voxy-border bg-voxy-surface backdrop-blur-lg shadow-md"
        >
          <div className="flex items-center gap-3 mb-3">
            <Sparkles className="text-voxy-primary" size={20} />
            <h3 className="text-lg font-semibold text-voxy-text">Summary</h3>
          </div>
          <p className="text-sm text-voxy-muted leading-relaxed">
            {summary || "No summary available."}
          </p>
        </motion.section>
      </motion.div>
    </ProtectedRoute>
  );
}
