import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./providers/StoreProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AppInitializer from "./components/AppInitializer";
import { ToastContainer } from "react-toastify";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VoxyAi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
    >
      <head>
    
        <script
          dangerouslySetInnerHTML={{
            __html: `(function(){try{
              var theme = localStorage.getItem('theme');
              if(theme === 'light'){ document.documentElement.classList.add('light'); return; }
              if(theme === 'dark'){ document.documentElement.classList.remove('light'); return; }
              if(window.matchMedia && window.matchMedia('(prefers-color-scheme: light)').matches){
                document.documentElement.classList.add('light');
              }
            }catch(e){/* silent */}})();`,
          }}
        />
      </head>

      <body>
        <StoreProvider>
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
            <ToastContainer position="top-right" autoClose={3000} theme="colored" />
            <AppInitializer />
            {children}
          </GoogleOAuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
