import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import StoreProvider from "./providers/StoreProvider";
import { GoogleOAuthProvider } from "@react-oauth/google";
import AppInitializer from "./components/AppInitializer";
import { ToastContainer } from "react-toastify";
import Preloader from "./components/preloader/SwarAiPreloader";
import { DarkLight } from "./components/DarkLightMood/DarkLight";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "VoxyAi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
    >

      <body>
        <StoreProvider>
          <GoogleOAuthProvider clientId={process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID!}>
            <ToastContainer position="top-right" autoClose={3000} theme="colored" />
            <AppInitializer />
            <Preloader/>
            <DarkLight/>
            {children}
          </GoogleOAuthProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
